// TheSportsDB renvoie les noms d'équipes en anglais → on les affiche en français.
// Les codes de qualif (ex. « 1F », « 3A/B/C/D/F ») ne sont pas dans la table → renvoyés tels quels.
const FR: Record<string, string> = {
  Argentina: 'Argentine',
  Australia: 'Australie',
  Austria: 'Autriche',
  Belgium: 'Belgique',
  'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
  'Bosnia-Herzegovina': 'Bosnie-Herzégovine',
  Brazil: 'Brésil',
  Cameroon: 'Cameroun',
  Canada: 'Canada',
  'Cape Verde': 'Cap-Vert',
  Chile: 'Chili',
  Colombia: 'Colombie',
  'Costa Rica': 'Costa Rica',
  Croatia: 'Croatie',
  Curacao: 'Curaçao',
  Curaçao: 'Curaçao',
  Czechia: 'Tchéquie',
  'Czech Republic': 'Tchéquie',
  Denmark: 'Danemark',
  Ecuador: 'Équateur',
  Egypt: 'Égypte',
  England: 'Angleterre',
  France: 'France',
  Germany: 'Allemagne',
  Ghana: 'Ghana',
  Greece: 'Grèce',
  Haiti: 'Haïti',
  Honduras: 'Honduras',
  Iran: 'Iran',
  Iraq: 'Irak',
  Italy: 'Italie',
  'Ivory Coast': "Côte d'Ivoire",
  "Cote d'Ivoire": "Côte d'Ivoire",
  Jamaica: 'Jamaïque',
  Japan: 'Japon',
  Jordan: 'Jordanie',
  'Korea Republic': 'Corée du Sud',
  'South Korea': 'Corée du Sud',
  Mexico: 'Mexique',
  Morocco: 'Maroc',
  Netherlands: 'Pays-Bas',
  'New Zealand': 'Nouvelle-Zélande',
  Nigeria: 'Nigeria',
  Norway: 'Norvège',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Peru: 'Pérou',
  Poland: 'Pologne',
  Portugal: 'Portugal',
  Qatar: 'Qatar',
  'Republic of Ireland': 'Irlande',
  'Saudi Arabia': 'Arabie saoudite',
  Scotland: 'Écosse',
  Senegal: 'Sénégal',
  Serbia: 'Serbie',
  Slovakia: 'Slovaquie',
  Slovenia: 'Slovénie',
  'South Africa': 'Afrique du Sud',
  Spain: 'Espagne',
  Sweden: 'Suède',
  Switzerland: 'Suisse',
  Tunisia: 'Tunisie',
  Turkey: 'Turquie',
  Türkiye: 'Turquie',
  Ukraine: 'Ukraine',
  'United Arab Emirates': 'Émirats arabes unis',
  'United States': 'États-Unis',
  USA: 'États-Unis',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Ouzbékistan',
  Wales: 'Pays de Galles',
};

export function frTeam(name?: string | null): string {
  if (!name) return '';
  return FR[name] ?? FR[name.trim()] ?? name;
}
